### ISSUE TITLE
cant login. login page is blank (flatpak)

### ISSUE THREAD

**Issue by k3mist** [Mastermindzh/tidal-hifi#661]
i ran 
```
flatpak install flathub com.mastermindzh.tidal-hifi
```

when i click login on the home page the redirect is blank. i know this is just a wrapper for the website but any ideas?

in chromium i was redirected to a captcha before it took me to the login. maybe thats the issue?

<img width="1401" height="1151" alt="Image" src="https://github.com/user-attachments/assets/cff52447-8b1c-49a8-99b7-4c3d79f6b776" />

**Comment by Mastermindzh** [comment]
Please update to a compatible version 😄 
This bug was fixed a while ago.

**Comment by k3mist** [comment]
the version on flathub is not the latest? 

<img width="906" height="74" alt="Image" src="https://github.com/user-attachments/assets/64bf800d-694a-45c3-83c1-11a410255127" />

<img width="677" height="351" alt="Image" src="https://github.com/user-attachments/assets/3fb762b2-6082-4bb1-8717-bf890fdc6113" />

**Comment by k3mist** [comment]
im on kde neon if that helps

<img width="769" height="719" alt="Image" src="https://github.com/user-attachments/assets/7918e449-6149-4d3b-9066-09d5e8703ec7" />

i also tried all of these with no luck.

```    Commit: 585c641dca85f27c698b7166b16921d0e6a606cdbe8c1f8852cdd50cc50412e1
   Subject: release: 5.19.0 (#44) (09f2424cefcf)
      Date: 2025-04-22 22:30:33 +0000

    Commit: cfaac923219310f7836d5dbba282804ccdec311942bb8149427bf5a0f44d89e9
   Subject: release: 5.18.2 (#43) (6bcaa9bd)
      Date: 2025-03-30 19:14:18 +0000

    Commit: 12d27ae06bb4416bc997904e7b839cdae719a105ffc4abd9343217d8a61ed39a
   Subject: 5.18.0 (#41) (27ab450b)
      Date: 2025-03-18 09:46:38 +0000

    Commit: 897a5b1577cd8a322c581a3599247cfaa0daa43ffa3f9729fce070c94622c403
   Subject: Fix MPRIS issue (#40) (a5fe6da6)
      Date: 2025-03-08 20:39:55 +0000

    Commit: 73510104346028d363e0a41df506e14ebb8af48030dcf55368f3e6b421b77bdc
   Subject: Add symbolic icon (#38) (eddc4f50)
      Date: 2024-12-04 03:11:58 +0000

    Commit: 5d9c04bffabee8445e6112463ce6a7f054bf4f5e51a8613e4594b5639801054a
   Subject: upd: 5.17.0 (7a6b1863)
      Date: 2024-10-28 18:46:41 +0000

    Commit: e75f3818dc3b58d7c2f5ccffabfdd688d708e07784f413a2d82cc0b149089437
   Subject: Update Electron base-version and freedesktop runtime-version to 24.08 (#34) (d58df339)
      Date: 2024-09-30 11:42:44 +0000

    Commit: eb344a29539f91638d858bc00f357db4309f25f1acabcab9e91f38ae7f414714
   Subject: release: 5.16.0 (244689d0)
      Date: 2024-08-12 12:38:25 +0000
```

**Comment by bragetranvik** [comment]
The bug is not fixed yet. I'm using Flatpak version 5.20.0 on Ubuntu 24.04.3.
Was able to log in with `flatpak run com.mastermindzh.tidal-hifi -v --no-sandbox` though.

**Comment by k3mist** [comment]
> The bug is not fixed yet. I'm using Flatpak version 5.20.0 on Ubuntu 24.04.3. Was able to log in with `flatpak run com.mastermindzh.tidal-hifi -v --no-sandbox` though.

thanks for the tip. ill give that a shot

edit; works! thanks a bunch. also found you can restart without the need to --no-sandbox and you're still logged in

**Comment by EmilProgramer** [comment]
works for me on elementaryos 8

**Comment by fayeinmay** [comment]
Don't know why this is closed, it's still an unfixed issue.

<img width="2516" height="1168" alt="Image" src="https://github.com/user-attachments/assets/f3f13917-9861-40a0-9b79-286cdf0792b0" />

**Comment by ste-goldstein** [comment]
Also worked on Arch, without flatpak:
`tidal-hifi --no-sandbox`

**Comment by Mastermindzh** [comment]
@fayeinmay, 

Try launching it with `tidal-hifi --no-sandbox` or `com.mastermindzh.tidal-hifi --no-sandbox` if you're using the flatpak.

It's a known issue and the workaround is well documented. That's why we close these issues after the original poster figures out the workaround 😄

**Comment by fayeinmay** [comment]
@Mastermindzh Ah, well, yea, I didn't see them original in the GitHub wiki. Forget I said anything then haha.
Though you could link to the Wiki in the README for the future?

**Comment by Mastermindzh** [comment]
No worries! 
If that helps I'll be happy to drop wiki links too :)
